In [1]:
from keras.datasets import fashion_mnist

In [2]:
# load dataset
(trainX, trainy), (testX, testy) = fashion_mnist.load_data()


4431872/4422102 [==============================] - 0s 0us/step


In [3]:
# summarize loaded dataset
print('Train: X=%s, y=%s' % (trainX.shape, trainy.shape))
print('Test: X=%s, y=%s' % (testX.shape, testy.shape))

Train: X=(60000, 28, 28), y=(60000,)
Test: X=(10000, 28, 28), y=(10000,)


In [33]:
X_train=trainX.reshape(trainX.shape[0],28*28).T
X_train=X_train/255

In [34]:
X_train.shape

(784, 60000)

In [4]:
import numpy as np
a=np.array([10,20,30])
b=np.array([10,30,40])
a*b

array([ 100,  600, 1200])

In [5]:
#num of layers including ip layer 
num_layers=int(input("No. of layers: "))
#enter space sep no of neuron in each layer 1st entry is 784 and last should be 10
layer_neurons=[int(x) for x in input().split()]

assert layer_neurons[0]==784
assert layer_neurons[-1]==10



No. of layers: 6
784 3 5 4 2 10


In [6]:
def Weight_init(op,ip):
  return np.random.randn(op,ip)


In [7]:
def Neuralnet_init(layer_neurons,num_layers):
        W = {}
        b = {}
        for i in range(0, num_layers - 1):
            W[i + 1] = Weight_init(layer_neurons[i + 1], layer_neurons[i])
            b[i + 1] = np.zeros((layer_neurons[i + 1], 1))
        return W,b

In [35]:
W,b=Neuralnet_init(layer_neurons,num_layers)
print(W)

{1: array([[ 0.85612392, -1.03242826,  2.3365149 , ...,  0.09284945,
         0.36987878, -0.11253304],
       [ 1.06791053, -0.84925224,  0.0938871 , ...,  0.68255356,
        -1.86499304,  0.52445648],
       [ 1.02197586,  0.16276927, -0.78093541, ..., -0.77104996,
        -1.27875796,  0.60799908]]), 2: array([[-0.48510836, -1.63746124,  1.07501511],
       [ 1.07994628,  0.49017584, -0.20398836],
       [ 1.62680405,  0.37625328, -1.12385396],
       [ 2.37305511, -1.50952518, -1.78303358],
       [ 1.26781294, -0.14783591,  0.50582994]]), 3: array([[-0.1287995 , -0.85971128, -1.74362567, -0.31292612, -1.87813028],
       [ 0.86488902, -0.18772401, -0.22197332, -0.93028761,  0.66664803],
       [-0.53661906, -0.18957412, -0.01811235,  1.79783836,  1.08774668],
       [ 1.42767407,  0.42598048,  0.46476386, -0.77678265,  1.4748399 ]]), 4: array([[ 0.22440229,  0.82740786, -0.1053553 , -1.23050888],
       [-1.40548616, -0.3851634 , -0.53961319,  0.24880351]]), 5: array([[ 0.0974042

In [9]:
W[1].shape

(3, 784)

In [16]:
def sigmoid(z):
  return 1/1+np.exp(-(z))


In [36]:
def F_Prop(X_train, W, b,num_layers):
        """
        Forward Propogation
         
        """
        
        # A - Preactivations
        # H - Activations
        X = X_train[:,0]
        A = {}
        H={}
        H[0] = X
        #A[0] = X
        for l in range(0, num_layers - 2):
                Wh = W[l + 1]
                bh = b[l + 1]
                A[l + 1] = np.add(np.matmul(Wh, H[l]), bh)
                print(A[l+1])
                H[l + 1] = sigmoid(A[l + 1])
            

      
        Wo = W[num_layers-1]
        bo = b[num_layers - 1]
        A[num_layers - 1] = np.add(np.dot(Wo, H[num_layers - 2]), bo)

        Ypred = sigmoid(A[num_layers - 1])
        H[num_layers - 1] = Ypred
        return Ypred, H, A

In [37]:
ypred,h,a= F_Prop(X_train, W, b,num_layers)

[[-25.80965421  16.03183195  10.50479216]
 [-25.80965421  16.03183195  10.50479216]
 [-25.80965421  16.03183195  10.50479216]]
[[-1.69498955e+11 -1.04755461e+00 -1.04758320e+00]
 [ 2.21046491e+11  1.36613391e+00  1.36617120e+00]
 [ 1.42258998e+11  8.79203465e-01  8.79227464e-01]
 [-1.48779761e+11 -9.19503742e-01 -9.19528841e-01]
 [ 2.63062766e+11  1.62580715e+00  1.62585153e+00]]
[[       -inf -7.38782553 -7.38781379]
 [        nan  0.31499704  0.31500715]
 [        nan  5.27875495  5.27881687]
 [        nan  5.72987185  5.72991776]]
[[           nan   362.99152283   362.98725594]
 [           nan -2273.8942716  -2273.86758097]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in matmul


In [38]:
h
a

{1: array([[-25.80965421,  16.03183195,  10.50479216],
        [-25.80965421,  16.03183195,  10.50479216],
        [-25.80965421,  16.03183195,  10.50479216]]),
 2: array([[-1.69498955e+11, -1.04755461e+00, -1.04758320e+00],
        [ 2.21046491e+11,  1.36613391e+00,  1.36617120e+00],
        [ 1.42258998e+11,  8.79203465e-01,  8.79227464e-01],
        [-1.48779761e+11, -9.19503742e-01, -9.19528841e-01],
        [ 2.63062766e+11,  1.62580715e+00,  1.62585153e+00]]),
 3: array([[       -inf, -7.38782553, -7.38781379],
        [        nan,  0.31499704,  0.31500715],
        [        nan,  5.27875495,  5.27881687],
        [        nan,  5.72987185,  5.72991776]]),
 4: array([[           nan,   362.99152283,   362.98725594],
        [           nan, -2273.8942716 , -2273.86758097]]),
 5: array([[ nan,  inf,  inf],
        [ nan,  inf,  inf],
        [ nan,  inf,  inf],
        [ nan,  inf,  inf],
        [ nan, -inf, -inf],
        [ nan, -inf, -inf],
        [ nan,  inf,  inf],
        

In [32]:
h

{0: array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   1,   0,   0,  13,  73,   0,   0,   1,
          4,   0,   0,   0,   0,   1,   1,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   3,   0,  36, 136, 127,  62,
         54,   0,   0,   0,   1,   3,   4,   0,   0,   3,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   6,   0, 102, 204,
        176, 134, 144, 123,  23,   0,   0,   0,   0,  12,  10,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0, 

In [23]:
ypred

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])